Выполнил задания
Crashroma2009/homework pull request #1
Opened 2021-05-22 12:12 UTC by Crashroma2009

2021-05-23 10:24 UTC, n05tr0m0 requested changes
Оставил комментарии

2021-05-23 10:24 UTC, n05tr0m0 commented on 1_if1.py
> +    print('Только детский сад')
У тебя тут написаны принты, но в условии задачи сказано, возвращать, а это `return`

2021-05-23 10:24 UTC, n05tr0m0 commented on 2_if2.py
> +         print('0')
Та же проблема с принтами.

2021-05-23 10:24 UTC, n05tr0m0 commented on 2_if2.py
> +    if str1 != str(str1) and str2 != str(str2):
Для проверки типа данных используй `isinstance()`

2021-05-23 10:24 UTC, n05tr0m0 commented on 2_if2.py
> +  main(str1, str2)
Можно не переназначать переменные каждый раз, а написать следующим образом:

```python
print(main('Python', 'learn'))
print(main('Moscow', 'Moscow'))
# и так далее
```

2021-05-23 10:24 UTC, n05tr0m0 commented on 3_for.py
> +    ratings = 0
На самом деле тут можно упростить.

Попробуй подумать как решить задачу одним for циклом.

Подсказка: использовать дополнительный список, для записи оценок.

2021-05-23 10:24 UTC, n05tr0m0 commented on 4_while1.py
> +  while vopros != otvet:
Правило хорошего тона, не писать наименование переменных транслитом русских слов, необходимо писать наименования переменны, классов и функций на английском.

2021-05-23 10:24 UTC, n05tr0m0 commented on 4_while1.py
> +otvet = 'Хорошо'
Тут переменная используется вне функции.

Внутри функци можно сразу в if указать вопрос != 'Хорошо'

2021-05-23 10:24 UTC, n05tr0m0 commented on 5_while2.py
> +    answers_dict = input('Задайте вопрос ')
Тут не обязательно использовать переменную. Можно просто написать` input('Задайте вопрос: ')`

2021-05-23 10:24 UTC, n05tr0m0 commented on 8_ephem_bot.py
> +    user_text = update.message.text
Сплит можно использовать сразу: `user_text = update.message.text.split()`

2021-05-23 10:24 UTC, n05tr0m0 commented on 8_ephem_bot.py
> +    s1 = s[1]
Лучше давать понятные наименования переменных, чтобы через пару месяцев или другим программистом было легче читать код.
допустим: `planet_name = user_text[1]`

2021-05-23 10:24 UTC, n05tr0m0 commented on 8_ephem_bot.py
> +    mybot = Updater("1851936710:AAGwiPLETcFRwQo50sxQBa51chpi-OR_OA8", request_kwargs=PROXY, use_context=True)
Не хорошо вписывать ключи в файлы в открытом виде.
На интенсивен первого дня про это рассказывали.

2021-05-25 08:19 UTC, n05tr0m0 reviewed
Прокомментировал

2021-05-25 08:19 UTC, n05tr0m0 commented on 2_if2.py
> +    if isinstance(str1, int) and isinstance(str2, int):
Нет, тебе необходимо проверить, если вводные данные не строки,  а значит:
```python
if not (isinstance(str1, str) and (isinstance(str2, str)):
```
Посмотри, осмысли и подумай почему выражение в скобках.

2021-05-25 08:19 UTC, n05tr0m0 commented on 4_while1.py
> +  while response.lower() != ('Хорошо').lower():
А зачем строку "хорошо", брать в скобки?
Не нужно результирующую сроку приводить к нижнему регистру, можно просто написать: `"хорошо"` и всё :)

2021-05-25 08:19 UTC, n05tr0m0 commented on 8_ephem_bot.py
> +    mybot = Updater(KeyBot.key, request_kwargs=PROXY, use_context=True)
Вообще так тоже можно, конечно, но я бы сделал какой-нибудь файл типа `settings.py` или `config.py` и там уже написал описал переменные.

2021-05-25 16:25 UTC, Crashroma2009 commented on 2_if2.py
> +  print(main(3, 54)
Мой косяк!

2021-05-25 17:25 UTC, n05tr0m0 approved these changes

2021-05-25 17:25 UTC, n05tr0m0 commented on .vscode/settings.json
> +{
ты забыл в `.gitignnore` добавить папку` .vscode/`

2021-05-25 17:25 UTC, merged